apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-manifest
data:
  mongodb.yaml: |
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: mongodb-pvc
    spec:
      storageClassName: standard
      accessModes:
      - ReadWriteOnce
      volumeMode: Filesystem
      resources:
        requests:
          storage: 10Gi  # Adjust the size as needed
    ---
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: my-release-mongodb
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: my-release-mongodb
      template:
        metadata:
          labels:
            app: my-release-mongodb
        spec:
          containers:
          - name: mongodb
            image: mongo:latest
            ports:
            - containerPort: 27017
            env:
            - name: MONGODB_ROOT_PASSWORD
              value: "isj21fNdSX"  # Set the root password
            - name: MONGODB_USERNAME
              value: "root"  # Username
            - name: MONGODB_DATABASE
              value: "test"  # Database name
            volumeMounts:
            - mountPath: /bitnami/mongodb  # Mount path in the container
              name: mongodb-storage
          volumes:
          - name: mongodb-storage
            persistentVolumeClaim:
              claimName: mongodb-pvc  # Reference to the PVC
    ---
    apiVersion: v1
    kind: Service
    metadata:
      name: my-release-mongodb
    spec:
      type: ClusterIP
      ports:
        - port: 27017
          targetPort: 27017
      selector:
        app: my-release-mongodb

